import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost/signin');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Manage Stations View, add,' }).click();
  await page.getByRole('button', { name: 'Add Station' }).click();
  await page.getByRole('textbox', { name: 'Station Name' }).click();
  await page.getByRole('textbox', { name: 'Station Name' }).fill('Repsol');
  await page.getByRole('textbox', { name: 'Location' }).click();
  await page.getByRole('textbox', { name: 'Location' }).fill('Aveiro');
  await page.locator('div').filter({ hasText: /^\+− Leaflet$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^\+− Leaflet$/ }).nth(1).click();
  await page.getByRole('button', { name: 'Create Station' }).click();
  await page.getByRole('button', { name: 'View Details' }).click();
  await page.getByRole('button', { name: 'Add Charger' }).click();
  await page.getByRole('textbox', { name: 'Charger Type' }).click();
  await page.getByRole('spinbutton', { name: 'Power (kW)' }).click();
  await page.getByRole('spinbutton', { name: 'Power (kW)' }).fill('25');
  await page.getByRole('button', { name: 'Add Charger' }).click();
  await page.getByRole('button', { name: 'Add Charger' }).click();
  await page.getByRole('spinbutton', { name: 'Power (kW)' }).click();
  await page.getByRole('spinbutton', { name: 'Power (kW)' }).fill('26');
  await page.getByRole('combobox').click();
  await page.getByLabel('Out of Service').getByText('Out of Service').click();
  await page.getByRole('button', { name: 'Add Charger' }).click();
  await page.getByRole('button', { name: 'Logout' }).click();
});