import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost/signin');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Manage Stations View, add,' }).click();
  await page.getByRole('button', { name: 'Add Station' }).click();
  await page.getByRole('textbox', { name: 'Station Name' }).click();
  await page.getByRole('textbox', { name: 'Station Name' }).fill('Repsol');
  await page.getByRole('textbox', { name: 'Location' }).click();
  await page.getByRole('textbox', { name: 'Location' }).fill('Aveiro');
  await page.locator('div').filter({ hasText: /^\+− Leaflet$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^\+− Leaflet$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^\+− Leaflet$/ }).nth(1).click();
  await page.getByRole('button', { name: 'Marker' }).click();
  await page.getByRole('button', { name: 'Create Station' }).click();
  await page.getByRole('button', { name: 'View Details' }).click();
  await page.getByRole('button', { name: 'Add Charger' }).click();
  await page.getByRole('button', { name: 'Add Charger' }).click();
  await page.getByRole('button', { name: 'Add Charger' }).click();
  await page.getByRole('combobox').click();
  await page.getByLabel('Under Maintenance').getByText('Under Maintenance').click();
  await page.getByRole('button', { name: 'Add Charger' }).click();
  await page.getByRole('button', { name: 'Logout' }).click();
  await page.getByRole('link', { name: 'Sign up' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('martim');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('martim@ua.pt');
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('Martim');
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill('Santos');
  await page.getByRole('combobox', { name: 'User Type' }).click();
  await page.getByText('Manage your charging stations', { exact: true }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123123');
  await page.getByRole('button', { name: 'Sign Up' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('martim123');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Username' }).dblclick();
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).fill('martim');
  await page.locator('div').filter({ hasText: /^Password$/ }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('button', { name: 'Claim Station' }).click();
  await page.getByRole('button', { name: 'Add Charging Station' }).click();
  await page.getByRole('combobox').click();
  await page.getByLabel('Out of Service').getByText('Out of Service').click();
  await page.getByRole('button', { name: 'Add Charger' }).click();
  await page.getByRole('button', { name: 'Logout' }).click();
});